kind: pipeline
type: docker
name: default

environment:
  {}

steps:

- name: print-env
  image: busybox:1
  when:
    event:
    - tag
    - push
  commands:
  - env

- name: publish-image
  image: plugins/docker
  when:
    event:
    - tag
  settings:
    dockerfile: debian.dockerfile
    context: .
    debug: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: opertusmundi/ipr
    tags:
    - "${DRONE_SEMVER_SHORT}"
    - "${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}"
    mirror: http://registry-mirror:5000
    build_args:
    - VERSION=${DRONE_SEMVER_SHORT}
